// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq9TwiPu4LHs6yZ18vhejjkMGvPEWITxQ',
    appId: '1:149661034289:web:07adbf51d2687b931e7210',
    messagingSenderId: '149661034289',
    projectId: 'sneaker-shop-6ba74',
    authDomain: 'sneaker-shop-6ba74.firebaseapp.com',
    storageBucket: 'sneaker-shop-6ba74.firebasestorage.app',
    measurementId: 'G-NGZW9WP1GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsZlYYgZMXkx3MeITOx2U99AvSeyDEMk',
    appId: '1:149661034289:android:6c3e6d53afa145021e7210',
    messagingSenderId: '149661034289',
    projectId: 'sneaker-shop-6ba74',
    storageBucket: 'sneaker-shop-6ba74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2coXNHV4nHMLzr69XdbIZ_GxbKSigTDM',
    appId: '1:149661034289:ios:8fdbddaf94dd9f5a1e7210',
    messagingSenderId: '149661034289',
    projectId: 'sneaker-shop-6ba74',
    storageBucket: 'sneaker-shop-6ba74.firebasestorage.app',
    iosClientId: '149661034289-ghakt3i0uqjleekj06ts0111589b85bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2coXNHV4nHMLzr69XdbIZ_GxbKSigTDM',
    appId: '1:149661034289:ios:8fdbddaf94dd9f5a1e7210',
    messagingSenderId: '149661034289',
    projectId: 'sneaker-shop-6ba74',
    storageBucket: 'sneaker-shop-6ba74.firebasestorage.app',
    iosClientId: '149661034289-ghakt3i0uqjleekj06ts0111589b85bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq9TwiPu4LHs6yZ18vhejjkMGvPEWITxQ',
    appId: '1:149661034289:web:906833b3ff4f491c1e7210',
    messagingSenderId: '149661034289',
    projectId: 'sneaker-shop-6ba74',
    authDomain: 'sneaker-shop-6ba74.firebaseapp.com',
    storageBucket: 'sneaker-shop-6ba74.firebasestorage.app',
    measurementId: 'G-F2YYCDG8QL',
  );
}
